package de.hysky.skyblocker.skyblock.tabhud.util;

import de.hysky.skyblocker.skyblock.item.HeadTextures;
import de.hysky.skyblocker.utils.ItemUtils;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;

/**
 * Stores convenient shorthands for common ItemStack definitions
 */
public class Ico {
	public static final ItemStack MAP = Items.FILLED_MAP.getDefaultStack();
	public static final ItemStack NTAG = Items.NAME_TAG.getDefaultStack();
	public static final ItemStack EMERALD = Items.EMERALD.getDefaultStack();
	public static final ItemStack MAGMA_CREAM = Items.MAGMA_CREAM.getDefaultStack();
	public static final ItemStack AMETHYST_SHARD = Items.AMETHYST_SHARD.getDefaultStack();
	public static final ItemStack CLOCK = Items.CLOCK.getDefaultStack();
	public static final ItemStack DIA_SWORD = Items.DIAMOND_SWORD.getDefaultStack();
	public static final ItemStack DBUSH = Items.DEAD_BUSH.getDefaultStack();
	public static final ItemStack VILLAGER = Items.VILLAGER_SPAWN_EGG.getDefaultStack();
	public static final ItemStack SPAWN_EGG = Items.GHAST_SPAWN_EGG.getDefaultStack();
	public static final ItemStack GOLDEN_APPLE = Items.GOLDEN_APPLE.getDefaultStack();
	public static final ItemStack COMPASS = Items.COMPASS.getDefaultStack();
	public static final ItemStack SUGAR = Items.SUGAR.getDefaultStack();
	public static final ItemStack IRON_HOE = Items.IRON_HOE.getDefaultStack();
	public static final ItemStack GOLDEN_HOE = Items.GOLDEN_HOE.getDefaultStack();
	public static final ItemStack GOLD = Items.GOLD_INGOT.getDefaultStack();
	public static final ItemStack IRON = Items.IRON_INGOT.getDefaultStack();
	public static final ItemStack BONE = Items.BONE.getDefaultStack();
	public static final ItemStack SIGN = Items.OAK_SIGN.getDefaultStack();
	public static final ItemStack FISH_ROD = Items.FISHING_ROD.getDefaultStack();
	public static final ItemStack STONE_SWORD = Items.STONE_SWORD.getDefaultStack();
	public static final ItemStack IRON_SWORD = Items.IRON_SWORD.getDefaultStack();
	public static final ItemStack LANTERN = Items.LANTERN.getDefaultStack();
	public static final ItemStack COOKIE = Items.COOKIE.getDefaultStack();
	public static final ItemStack POTION = Items.POTION.getDefaultStack();
	public static final ItemStack S_POTION = Items.SPLASH_POTION.getDefaultStack();
	public static final ItemStack BARRIER = Items.BARRIER.getDefaultStack();
	public static final ItemStack PLAYER = Items.PLAYER_HEAD.getDefaultStack();
	public static final ItemStack FAIRY_SOUL = ItemUtils.createSkull(HeadTextures.FAIRY_SOUL);
	public static final ItemStack WATER = Items.WATER_BUCKET.getDefaultStack();
	public static final ItemStack LEATHER = Items.LEATHER.getDefaultStack();
	public static final ItemStack MITHRIL = Items.PRISMARINE_CRYSTALS.getDefaultStack();
	public static final ItemStack REDSTONE = Items.REDSTONE.getDefaultStack();
	public static final ItemStack CAMPFIRE = Items.CAMPFIRE.getDefaultStack();
	public static final ItemStack STRING = Items.STRING.getDefaultStack();
	public static final ItemStack WITHER = Items.WITHER_SKELETON_SKULL.getDefaultStack();
	public static final ItemStack FLESH = Items.ROTTEN_FLESH.getDefaultStack();
	public static final ItemStack MUTTON = Items.MUTTON.getDefaultStack();
	public static final ItemStack DRAGON = Items.DRAGON_HEAD.getDefaultStack();
	public static final ItemStack DIAMOND = Items.DIAMOND.getDefaultStack();
	public static final ItemStack ICE = Items.ICE.getDefaultStack();
	public static final ItemStack CHEST = Items.CHEST.getDefaultStack();
	public static final ItemStack COMMAND = Items.COMMAND_BLOCK.getDefaultStack();
	public static final ItemStack SKULL = Items.SKELETON_SKULL.getDefaultStack();
	public static final ItemStack BOOK = Items.WRITABLE_BOOK.getDefaultStack();
	public static final ItemStack FURNACE = Items.FURNACE.getDefaultStack();
	public static final ItemStack CHESTPLATE = Items.IRON_CHESTPLATE.getDefaultStack();
	public static final ItemStack L_CHESTPLATE = Items.LEATHER_CHESTPLATE.getDefaultStack();
	public static final ItemStack B_ROD = Items.BLAZE_ROD.getDefaultStack();
	public static final ItemStack B_POWDER = Items.BLAZE_POWDER.getDefaultStack();
	public static final ItemStack BOW = Items.BOW.getDefaultStack();
	public static final ItemStack COPPER = Items.COPPER_INGOT.getDefaultStack();
	public static final ItemStack NETHERITE_UPGRADE_ST = Items.NETHERITE_UPGRADE_SMITHING_TEMPLATE.getDefaultStack();
	public static final ItemStack COMPOSTER = Items.COMPOSTER.getDefaultStack();
	public static final ItemStack SAPLING = Items.OAK_SAPLING.getDefaultStack();
	public static final ItemStack SEEDS = Items.WHEAT_SEEDS.getDefaultStack();
	public static final ItemStack LODESTONE = Items.LODESTONE.getDefaultStack();
	public static final ItemStack STONE_PICKAXE = Items.STONE_PICKAXE.getDefaultStack();
	public static final ItemStack IRON_PICKAXE = Items.IRON_PICKAXE.getDefaultStack();
	public static final ItemStack NETHER_STAR = Items.NETHER_STAR.getDefaultStack();
	public static final ItemStack HEART_OF_THE_SEA = Items.HEART_OF_THE_SEA.getDefaultStack();
	public static final ItemStack EXPERIENCE_BOTTLE = Items.EXPERIENCE_BOTTLE.getDefaultStack();
	public static final ItemStack PINK_DYE = Items.PINK_DYE.getDefaultStack();
	public static final ItemStack LIME_DYE = Items.LIME_DYE.getDefaultStack();
	public static final ItemStack GRAY_DYE = Items.GRAY_DYE.getDefaultStack();
	public static final ItemStack ENCHANTED_BOOK = Items.ENCHANTED_BOOK.getDefaultStack();
	public static final ItemStack SPIDER_EYE = Items.SPIDER_EYE.getDefaultStack();
	public static final ItemStack BLUE_ICE = Items.BLUE_ICE.getDefaultStack();
	public static final ItemStack JUNGLE_SAPLING = Items.JUNGLE_SAPLING.getDefaultStack();
	public static final ItemStack ENCHANTING_TABLE = Items.ENCHANTING_TABLE.getDefaultStack();
	public static final ItemStack BREWING_STAND = Items.BREWING_STAND.getDefaultStack();
	public static final ItemStack CRAFTING_TABLE = Items.CRAFTING_TABLE.getDefaultStack();
	public static final ItemStack PAINTING = Items.PAINTING.getDefaultStack();
	public static final ItemStack E_PEARL = Items.ENDER_PEARL.getDefaultStack();
	public static final ItemStack FEATHER = Items.FEATHER.getDefaultStack();
	public static final ItemStack E_CHEST = Items.ENDER_CHEST.getDefaultStack();
	public static final ItemStack MYCELIUM = Items.MYCELIUM.getDefaultStack();
	public static final ItemStack SALMON_BUCKET = Items.SALMON_BUCKET.getDefaultStack();
	public static final ItemStack TROPICAL_FISH_BUCKET = Items.TROPICAL_FISH_BUCKET.getDefaultStack();
	public static final ItemStack STRIPPED_SPRUCE_WOOD = Items.STRIPPED_SPRUCE_WOOD.getDefaultStack();
	public static final ItemStack MANGROVE_LOG = Items.MANGROVE_LOG.getDefaultStack();
	public static final ItemStack AATROX_BATPHONE_SKULL = ItemUtils.createSkull(HeadTextures.AATROX_BATPHONE);
	public static final ItemStack REVENANT_HORROR_SKULL = ItemUtils.createSkull(HeadTextures.REVENANT_HORROR);
	public static final ItemStack TARANTULA_BROODFATHER_SKULL = ItemUtils.createSkull(HeadTextures.TARANTULA_BROODFATHER);
	public static final ItemStack SVEN_PACKMASTER_SKULL = ItemUtils.createSkull(HeadTextures.SVEN_PACKMASTER);
	public static final ItemStack VOIDGLOOM_SERAPH_SKULL = ItemUtils.createSkull(HeadTextures.VOIDGLOOM_SERAPH);
	public static final ItemStack RIFTSTALKER_BLOODFIEND_SKULL = ItemUtils.createSkull(HeadTextures.RIFTSTALKER_BLOODFIEND);
	public static final ItemStack INFERNO_DEMONLORD_SKULL = ItemUtils.createSkull(HeadTextures.INFERNO_DEMONLORD);
	public static final ItemStack CATACOMBS_SKULL = ItemUtils.createSkull(HeadTextures.CATACOMBS);
	public static final ItemStack SKYBLOCK_ICON_SKULL = ItemUtils.createSkull(HeadTextures.SKYBLOCK_ICON);
	public static final ItemStack NETHERRACK = Items.NETHERRACK.getDefaultStack();
	public static final ItemStack KUUDRA_KEY_SKULL = ItemUtils.createSkull(HeadTextures.KUUDRA_KEY);
	public static final ItemStack HOT_KUUDRA_KEY_SKULL = ItemUtils.createSkull(HeadTextures.HOT_KUUDRA_KEY);
	public static final ItemStack BURNING_KUUDRA_KEY_SKULL = ItemUtils.createSkull(HeadTextures.BURNING_KUUDRA_KEY);
	public static final ItemStack FIERY_KUUDRA_KEY_SKULL = ItemUtils.createSkull(HeadTextures.FIERY_KUUDRA_KEY);
	public static final ItemStack INFERNAL_KUUDRA_KEY_SKULL = ItemUtils.createSkull(HeadTextures.INFERNAL_KUUDRA_KEY);
	public static final ItemStack PERFECT_JADE_SKULL = ItemUtils.createSkull(HeadTextures.PERFECT_JADE);
	public static final ItemStack PERFECT_AMBER_SKULL = ItemUtils.createSkull(HeadTextures.PERFECT_AMBER);
	public static final ItemStack PERFECT_TOPAZ_SKULL = ItemUtils.createSkull(HeadTextures.PERFECT_TOPAZ);
	public static final ItemStack PERFECT_SAPPHIRE_SKULL = ItemUtils.createSkull(HeadTextures.PERFECT_SAPPHIRE);
	public static final ItemStack PERFECT_AMETHYST_SKULL = ItemUtils.createSkull(HeadTextures.PERFECT_AMETHYST);
	public static final ItemStack PERFECT_JASPER_SKULL = ItemUtils.createSkull(HeadTextures.PERFECT_JASPER);
	public static final ItemStack PERFECT_RUBY_SKULL = ItemUtils.createSkull(HeadTextures.PERFECT_RUBY);
	public static final ItemStack PERFECT_OPAL_SKULL = ItemUtils.createSkull(HeadTextures.PERFECT_OPAL);
	public static final ItemStack PERFECT_ONYX_SKULL = ItemUtils.createSkull(HeadTextures.PERFECT_ONYX);
	public static final ItemStack PERFECT_AQUAMARINE_SKULL = ItemUtils.createSkull(HeadTextures.PERFECT_AQUAMARINE);
	public static final ItemStack PERFECT_CITRINE_SKULL = ItemUtils.createSkull(HeadTextures.PERFECT_CITRINE);
	public static final ItemStack PERFECT_PERIDOT_SKULL = ItemUtils.createSkull(HeadTextures.PERFECT_PERIDOT);
	public static final ItemStack CLAW_FOSSIL_SKULL = ItemUtils.createSkull(HeadTextures.CLAW_FOSSIL);
	public static final ItemStack SPINE_FOSSIL_SKULL = ItemUtils.createSkull(HeadTextures.SPINE_FOSSIL);
	public static final ItemStack CLUBBED_FOSSIL_SKULL = ItemUtils.createSkull(HeadTextures.CLUBBED_FOSSIL);
	public static final ItemStack UGLY_FOSSIL_SKULL = ItemUtils.createSkull(HeadTextures.UGLY_FOSSIL);
	public static final ItemStack HELIX_FOSSIL_SKULL = ItemUtils.createSkull(HeadTextures.HELIX_FOSSIL);
	public static final ItemStack FOOTPRINT_FOSSIL_SKULL = ItemUtils.createSkull(HeadTextures.FOOTPRINT_FOSSIL);
	public static final ItemStack WEBBED_FOSSIL_SKULL = ItemUtils.createSkull(HeadTextures.WEBBED_FOSSIL);
	public static final ItemStack TUSK_FOSSIL_SKULL = ItemUtils.createSkull(HeadTextures.TUSK_FOSSIL);
}
